INSERT INTO `products` (`productId`, `productName`, `productDescription`, `productPrice`, `productImgUrl`, `productStock`, `productStatus`, `productCategory`) VALUES
(1, 'Blusa Elegante Rosada', 'Blusa de manga corta en tono rosado pastel, ideal para ocasiones casuales', 450.00, '/img/productos/blusa_rosada.jpg', 15, 'ACT', 'GEN'),
(2, 'Vestido Floral Primavera', 'Vestido con estampado floral, corte A, perfecto para primavera', 850.00, '/img/productos/vestido_floral.jpg', 10, 'ACT', 'GEN'),
(3, 'Pantalón de Mezclilla', 'Pantalón jean clásico de corte recto, ajuste cómodo', 650.00, '/img/productos/pantalon_jean.jpg', 20, 'ACT', 'GEN'),
(4, 'Falda Plisada Negra', 'Falda midi plisada, elegante para oficina o eventos', 550.00, '/img/productos/falda_plisada.jpg', 12, 'ACT', 'GEN'),
(5, 'Tacones Nude Clásicos', 'Tacones de 7cm en tono nude, ideales para cualquier ocasión', 750.00, '/img/productos/tacones_nude.jpg', 8, 'ACT', 'GEN'),
(6, 'Sandalias Doradas', 'Sandalias con detalles dorados, perfectas para eventos', 680.00, '/img/productos/sandalias_doradas.jpg', 10, 'ACT', 'GEN'),
(7, 'Tenis Blancos Casuales', 'Tenis deportivos blancos, cómodos para uso diario', 580.00, '/img/productos/tenis_blancos.jpg', 15, 'ACT', 'GEN'),
(8, 'Flats Elegantes', 'Zapatos planos tipo bailarina en diferentes colores', 420.00, '/img/productos/flats.jpg', 18, 'ACT', 'GEN'),
(9, 'Aritos de Perla', 'Aretes pequeños con perla sintética, elegantes y discretos', 180.00, '/img/productos/aritos_perla.jpg', 25, 'ACT', 'GEN'),
(10, 'Aretes Largos Dorados', 'Aretes tipo cascada en tono dorado, llamativos', 250.00, '/img/productos/aretes_dorados.jpg', 20, 'ACT', 'GEN'),
(11, 'Aritos de Corazón', 'Pequeños aretes en forma de corazón, ideales para regalo', 150.00, '/img/productos/aritos_corazon.jpg', 30, 'ACT', 'GEN'),
(12, 'Cadena Delicada Oro', 'Cadena fina de 45cm en tono oro', 350.00, '/img/productos/cadena_oro.jpg', 15, 'ACT', 'GEN'),
(13, 'Collar con Dije Estrella', 'Collar con dije de estrella, ajustable', 280.00, '/img/productos/collar_estrella.jpg', 18, 'ACT', 'GEN'),
(14, 'Cadena Choker', 'Gargantilla ajustable en diferentes diseños', 320.00, '/img/productos/choker.jpg', 12, 'ACT', 'GEN'),
(15, 'Pulsera de Cristales', 'Pulsera elástica con cristales brillantes', 200.00, '/img/productos/pulsera_cristales.jpg', 22, 'ACT', 'GEN'),
(16, 'Brazalete Dorado', 'Brazalete rígido con detalles grabados', 380.00, '/img/productos/brazalete_dorado.jpg', 10, 'ACT', 'GEN'),
(17, 'Set de Pulseras Finas', 'Juego de 3 pulseras delgadas combinables', 280.00, '/img/productos/set_pulseras.jpg', 15, 'ACT', 'GEN'),
(18, 'Reloj Minimalista Rosado', 'Reloj de pulso con correa de cuero sintético rosado', 650.00, '/img/productos/reloj_rosado.jpg', 8, 'ACT', 'GEN'),
(19, 'Reloj Dorado Elegante', 'Reloj metálico dorado, resistente al agua', 850.00, '/img/productos/reloj_dorado.jpg', 6, 'ACT', 'GEN'),
(20, 'Reloj Digital Deportivo', 'Reloj digital con múltiples funciones', 480.00, '/img/productos/reloj_digital.jpg', 10, 'ACT', 'GEN'),
(21, 'Conjunto Bebé Niño', 'Set de pantalón y playera para bebé 0-12 meses', 380.00, '/img/productos/conjunto_bebe_nino.jpg', 15, 'ACT', 'BBY'),
(22, 'Vestido Niña Flores', 'Vestido infantil con estampado floral, tallas 2-6 años', 420.00, '/img/productos/vestido_nina.jpg', 12, 'ACT', 'BBY'),
(23, 'Pijama Suave Bebé', 'Pijama de algodón suave para bebé, diferentes diseños', 320.00, '/img/productos/pijama_bebe.jpg', 20, 'ACT', 'BBY'),
(24, 'Body Pack x3', 'Paquete de 3 bodies de colores para bebé', 450.00, '/img/productos/bodies_pack.jpg', 18, 'ACT', 'BBY'),
(25, 'Kit Recién Nacido Completo', 'Set completo: bodies, gorro, babero, mantas', 850.00, '/img/productos/kit_recien_nacido.jpg', 8, 'ACT', 'BBY'),
(26, 'Kit Baño Bebé', 'Kit con toalla con capucha, jabón y accesorios', 580.00, '/img/productos/kit_bano.jpg', 12, 'ACT', 'BBY'),
(27, 'Kit Alimentación', 'Set de platos, cubiertos y vaso para bebé', 420.00, '/img/productos/kit_alimentacion.jpg', 15, 'ACT', 'BBY'),
(28, 'Bandeja Silicona Colores', 'Bandeja con ventosa en silicona de grado alimenticio', 280.00, '/img/productos/bandeja_silicona.jpg', 20, 'ACT', 'BBY'),
(29, 'Plato Dividido Bebé', 'Plato con divisiones para diferentes alimentos', 220.00, '/img/productos/plato_dividido.jpg', 25, 'ACT', 'BBY'),
(30, 'Set Bandeja + Cubiertos', 'Bandeja antideslizante con set de cubiertos', 350.00, '/img/productos/set_bandeja.jpg', 15, 'ACT', 'BBY'),
(31, 'Babero Impermeable', 'Babero de silicona con bolsillo recolector', 180.00, '/img/productos/babero_silicona.jpg', 30, 'ACT', 'BBY'),
(32, 'Pack Baberos Tela x5', 'Paquete de 5 baberos de algodón con diferentes diseños', 250.00, '/img/productos/pack_baberos.jpg', 20, 'ACT', 'BBY'),
(33, 'Babero Bandana', 'Babero tipo pañuelo, moderno y funcional', 150.00, '/img/productos/babero_bandana.jpg', 25, 'ACT', 'BBY'),
(34, 'Mordedor Refrigerable', 'Mordedor seguro para aliviar encías, refrigerable', 120.00, '/img/productos/mordedor.jpg', 35, 'ACT', 'BBY'),
(35, 'Chupón Ortodóntico', 'Chupete anatómico con estuche protector', 150.00, '/img/productos/chupon.jpg', 40, 'ACT', 'BBY'),
(36, 'Termómetro Digital Bebé', 'Termómetro digital de lectura rápida', 280.00, '/img/productos/termometro.jpg', 15, 'ACT', 'BBY'),
(37, 'Cepillo Dental Bebé', 'Cepillo suave para primeros dientes', 100.00, '/img/productos/cepillo_bebe.jpg', 30, 'ACT', 'BBY'),
(38, 'Organizador Multiusos', 'Organizador de plástico con divisiones, ideal para cocina', 320.00, 'https://images.pexels.com/photos/4635231/pexels-photo-4635231.jpeg??w=290&h=250', 18, 'ACT', 'HOG'),
(39, 'Juego de Toallas x3', 'Set de 3 toallas de diferentes tamaños', 450.00, 'https://images.pexels.com/photos/4635231/pexels-photo-4635231.jpeg??w=290&h=250', 12, 'ACT', 'HOG'),
(40, 'Contenedores Herméticos Set', 'Set de 5 contenedores apilables con tapa hermética', 380.00, 'https://images.pexels.com/photos/4635231/pexels-photo-4635231.jpeg??w=290&h=250', 15, 'ACT', 'HOG'),
(41, 'Tapete Decorativo', 'Tapete antideslizante para cocina o baño', 280.00, 'https://images.pexels.com/photos/4635231/pexels-photo-4635231.jpeg??w=290&h=250', 20, 'ACT', 'HOG'),
(42, 'Dispensador Jabón Automático', 'Dispensador touch-free con sensor', 580.00, 'https://images.pexels.com/photos/4635231/pexels-photo-4635231.jpeg??w=290&h=250', 10, 'ACT', 'HOG'),
(43, 'Cortador Verduras Multiuso', 'Cortador manual con diferentes cuchillas intercambiables', 350.00, 'https://images.pexels.com/photos/4635231/pexels-photo-4635231.jpeg??w=290&h=250', 15, 'ACT', 'HOG'),
(44, 'Escurridor Plegable', 'Colador plegable de silicona, ahorra espacio', 280.00, 'https://images.pexels.com/photos/4635231/pexels-photo-4635231.jpeg??w=290&h=250', 17, 'ACT', 'HOG'),
(45, 'Abridor Eléctrico Latas', 'Abridor automático de latas, seguro y fácil', 420.00, 'https://images.pexels.com/photos/4635231/pexels-photo-4635231.jpeg??w=290&h=250', 6, 'ACT', 'HOG'),
(46, 'Set Cubiertos Acero', 'Juego de 24 piezas en acero inoxidable', 650.00, 'https://images.pexels.com/photos/4635231/pexels-photo-4635231.jpeg??w=290&h=250', 6, 'ACT', 'HOG');